adding check for matching signing algorithm of token
XenitAB/go-oidc-middleware pull request #229
Opened 2022-12-15 19:47 UTC by gitu

solves #228

2022-12-15 19:48 UTC, gitu commented
@simongottschlag can you have a look please

2022-12-15 21:17 UTC, simongottschlag requested changes
Hi @gitu!

Thank you so much for your contribution. Amzing work. :1st_place_medal: 

I've added a few comments to the PR. Please tell me if you don't agree with something and we'll take the conversation.

One important thing before merge will be to have a test that verifies your issue in `keyhandler_test.go`.

I may be a bit slow this and next week, but I'll do my best to continue the review as soon as possible when you're ready.

2022-12-15 21:17 UTC, simongottschlag commented on internal/oidc/keyhandler.go
> +		return key, err
error is nil, but returning error (linter will warn).

```suggestion
		return key, nil
```

2022-12-15 21:17 UTC, simongottschlag commented on internal/oidc/keyhandler.go
>  	"time"
Place the non-std lib import as follows:

```suggestion
	"context"
	"fmt"
	"net/http"
	"sync"
	"time"
	
	"github.com/lestrrat-go/jwx/jwa"
```

2022-12-15 21:17 UTC, simongottschlag commented on internal/oidc/keyhandler_test.go
>  }
I would like to add a new test that has two keys with the same `kid` but different `alg` and make sure this works and continues to work in the future.

2022-12-15 22:36 UTC, gitu commented on internal/oidc/oidc.go
> +	headers, err := getHeadersFromTokenString(tokenString)
I agree, did so.

2022-12-15 22:46 UTC, gitu commented
@simongottschlag thanks for your input, feel free to have a look again

2022-12-18 19:24 UTC, simongottschlag commented
@gitu I will be merging this into a separate branch and add a few fixup commits (for linting etc). Will ping you in the other PR and do my best not to screw up the merge to make sure your commits are pointing to you. :^)

2022-12-18 19:25 UTC, merged