Use Echo middleware rather than depend on Echo's bundled JWT middleware
XenitAB/go-oidc-middleware pull request #256
Opened 2023-05-04 14:54 UTC by bittrance

There are two reasons for this: 
1. The packaged middleware tends to return 400 rather than more correct 4XX codes
2. The second reason is that this switch helps #252.

2023-05-04 21:02 UTC, simongottschlag requested changes
I like it! Would like the module to be renamed as well as the files to remove `jwt`. An update to the readme with the change would be good as well.

2023-05-04 21:02 UTC, simongottschlag commented on oidcechojwt/echo_jwt_test.go
> +	echoMiddleware := toEchoHandler(parseToken, opts...)
`oidcHandler`

2023-05-04 21:02 UTC, simongottschlag commented on oidcechojwt/echo_jwt_test.go
> +	echoMiddleware := New[oidctesting.TestClaims](nil, opts...)
`oidcHandler`

2023-05-05 11:25 UTC, bittrance commented on examples/shared/server_echo_jwt.go
> +func RunEchoJWT[T any](echoMiddleware echo.MiddlewareFunc, address string, port int) error {
jwt naming removed. 

It is not a handler, tho. That concept exists in Echo as well. A middleware in Echo is a handler factory. See example in https://echo.labstack.com/cookbook/middleware/ . How about `echo.OidcMiddleware`?

2023-05-07 09:32 UTC, simongottschlag commented on examples/shared/server_echo_jwt.go
> +func RunEchoJWT[T any](echoMiddleware echo.MiddlewareFunc, address string, port int) error {
Yes, I'm fine with that!

2023-05-08 08:27 UTC, bittrance commented on examples/shared/server_echo_jwt.go
> +func RunEchoJWT[T any](echoMiddleware echo.MiddlewareFunc, address string, port int) error {
Fixed.

2023-05-08 08:27 UTC, bittrance commented on oidcechojwt/echo_jwt_test.go
> +func testGetEchoRouter(tb testing.TB, echoMiddleware echo.MiddlewareFunc) *echo.Echo {
Fixed, see above.

2023-05-08 08:27 UTC, bittrance commented on oidcechojwt/echo_jwt_test.go
> +	echoMiddleware := New[oidctesting.TestClaims](nil, opts...)
Fixed, see above.

2023-05-08 08:27 UTC, bittrance commented on oidcechojwt/echo_jwt_test.go
> +	echoMiddleware := toEchoHandler(parseToken, opts...)
Fixed, see above.

2023-05-08 12:57 UTC, simongottschlag approved these changes

2023-05-08 13:40 UTC, merged